-- ============================================================================
-- ClipMint — pipeline bug-hunt schema fixes (2026-09-20)
-- ============================================================================
-- Generated by the pipeline bug hunt (_audit/20-pipeline-bug-hunt.md). NOT yet
-- applied — run this in the Supabase SQL Editor (or via a new migration) and
-- confirm with `\d clips` that both changes are present.
--
-- 1. clips.render_error  — the backend's pipeline/db.py insert_clip_errors()
--    PATCHes this column to attach the render failure reason to a failed clip
--    row. The column was never created, so that helper silently failed
--    (caught + logged) the moment it was wired up. Adding it completes the
--    intended schema: the dashboard can show WHY a clip failed.
--
-- 2. Unique (job_id, clip_index, variant) — the pipeline's save-results step
--    deletes a job's rows then re-inserts to stay idempotent under retry, and
--    pipeline/db.py now verifies that reset actually succeeded. This index
--    makes the one-row-per-variant invariant hold at the DB level too, so a
--    duplicated dispatch can never double-count clips (quota: clips_used is
--    incremented from job.clips_count in the job-status webhook).
--    Duplicate rows (from runs before this index) are removed first, keeping
--    the oldest id per group.
-- ============================================================================

-- 1. Render-failure reason attached to failed clip rows (db.py:insert_clip_errors)
ALTER TABLE public.clips
    ADD COLUMN IF NOT EXISTS render_error TEXT;

-- 2. Backfill: drop any pre-existing duplicates (keep the oldest id per group)
--    so the unique index below can be created cleanly.
DELETE FROM public.clips a
USING public.clips b
WHERE a.job_id = b.job_id
  AND a.clip_index = b.clip_index
  AND a.variant = b.variant
  AND a.id > b.id;

-- 3. One delivered file per (job, clip index, aspect variant)
CREATE UNIQUE INDEX IF NOT EXISTS idx_clips_job_index_variant
    ON public.clips (job_id, clip_index, variant);